---
- name: Download foo.conf
  get_url:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo
    mode: '0440'

- name: install go-agent
  yum: 
    name: go-agent
    state: latest 

- name: start go-agent
  service:
      name: go-agent
      state: started
# tasks file for goCdAgent